/**
 * CONFIG FILE TO LINK PRODUCTION ENVIRONMENT VARIABLE FROM .env FILE TO THE CONFIG PACKAGE
 */

// IGNORE THIS
// is_development: {
//   __name: "IS_DEVELOPMENT",
//   __format: "json",
// },

export default {
  port: "PORT",
  node_env: "NODE_ENV",
  JWT_PUBLIC_KEY: "JWT_PUBLIC_KEY",
  JWT_SECRET_KEY: "JWT_SECRET_KEY",
  accessTokenTTL: "ACCESSTOKENTTL",
  refreshTokenTTL: "REFRESHTOKENTTL",
  MAILING_EMAIL: "MAILING_EMAIL",
  MAILING_PASSWORD: "MAILING_PASSWORD",
  CLOUDINARY_NAME: "CLOUDINARY_NAME",
  CLOUDINARY_API_KEY: "CLOUDINARY_API_KEY",
  CLOUDINARY_API_SECRET: "CLOUDINARY_API_SECRET",
  MONGODB_URI: "MONGODB_URI",
  saltWorkFactor: "SALTWORKFACTOR",
  whitelisted_origins: "WHITELISTED_ORIGINS",
};
